### ISSUE TITLE
Best way to use Python Threads

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb-web#212]
Hey folks!

Before I write up a how-to-guide, would you mind taking a look at this approach to using Python threads? Is this the best practice? I couldn't get it to work with cursors, so if that is a better method than not checking the same thread, I'm open to changing this!

Thanks!

```python
import duckdb
from threading import Thread, current_thread
import pandas as pd

def insert_from_thread(duckdb_con, results_df_dict):
  # Insert a row with the name of the thread
  thread_name = str(current_thread().name)
  results_df_dict[thread_name] = duckdb_con.execute("""INSERT INTO my_inserts VALUES (?)""", (thread_name,)).df()

duckdb_con = duckdb.connect(check_same_thread=False) # In Memory DuckDB
duckdb_con.execute("""CREATE OR REPLACE TABLE my_inserts (thread_name varchar)""")

thread_count = 10
threads = []
results_df_dict = {}

# Kick off multiple threads (in the same process) 
# Pass in the same connection as an argument, and an object to store the results
for i in range(thread_count):
    threads.append(Thread(target=insert_from_thread,
                            args=(duckdb_con, results_df_dict,),
                            name='my_thread_'+str(i)))

for i in range(thread_count):
    threads[i].start()

for i in range(thread_count):
    threads[i].join()

print(results_df_dict)
print(duckdb_con.execute("""SELECT * FROM my_inserts""").df())

```

**Comment by Mause** [comment]
Maybe use `concurrent.futures.ThreadPoolExecutor.map` instead?

**Comment by Alex-Monahan** [comment]
> Maybe use `concurrent.futures.ThreadPoolExecutor.map` instead?

Ah, thanks for the suggestion! Yes, we could use a simpler API than just the base threading library. I'm not sure if we would recommend using a map function in too many use cases though. Is there an example use case you had in mind?

The use case that I was thinking about for Python threads would be to have a long running thread or threads that loads data as it comes in, and another thread that runs analytical queries from time to time. I figured the base threading library might be a good fit for that kind of a thing. I am open to feedback though!

**Comment by Mause** [comment]
As to your last question, pretty sure the python interface just uses connections for cursors?

The map method could be used to demonstrate distributing a workload over a number of threads (scraping data from pages on a website, for example)

For your example though, maybe just a small example using flask and background jobs in that? Then werkzeug and flask can handle starting threads, etc

**Comment by Alex-Monahan** [comment]
Hi Folks!

Based on @hannes's advice around using cursors, I have tried a number of combinations of ways to try and get this to work, ideally without that "check_same_thread" parameter. None aside from the previous example were successful. I included all my attempts and error messages below. One root cause issue seems to be that a cursor does not inherit the "check_same_thread" setting from the connection, and it can't be set directly on the cursor.

My desired end goal is to have multiple threads in Python that will handle the MVCC. The use case I have in mind is lightweight HTAP: Constant random row inserts/updates/deletes from one or more threads, and another thread for analytical queries. Is that possible? Or would only inserts be guaranteed to not conflict with the analytical query thread?

Thanks as always! @pdet, is this something you could also take a quick look at too? I know I'm always asking you for help with the Python side of things - I do really appreciate it though!

1. Pass in the connection to each thread, and make a new cursor from that connection within the thread:
```python
import duckdb
from threading import Thread, current_thread
import pandas as pd

def insert_from_thread(duckdb_con, results_df_dict):
  # Insert a row with the name of the thread
  duckdb_cursor = duckdb_con.cursor() # Make a cursor within the thread
  thread_name = str(current_thread().name)
  results_df_dict[thread_name] = duckdb_cursor.execute("""INSERT INTO my_inserts VALUES (?)""", (thread_name,)).df()

duckdb_con = duckdb.connect(check_same_thread=False) # In Memory DuckDB
duckdb_con.execute("""CREATE OR REPLACE TABLE my_inserts (thread_name varchar)""")

thread_count = 3
threads = []
results_df_dict = {}

# Kick off multiple threads (in the same process) 
# Pass in the same connection as an argument, and an object to store the results
for i in range(thread_count):
    threads.append(Thread(target=insert_from_thread,
                            args=(duckdb_con, results_df_dict,),
                            name='my_thread_'+str(i)))

for i in range(thread_count):
    threads[i].start()

for i in range(thread_count):
    threads[i].join()

print(results_df_dict)
print(duckdb_con.execute("""SELECT * FROM my_inserts""").df())
```
```python
Exception in thread my_thread_2:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\new_duckdb\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\new_duckdb\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Alex\Documents\DuckDB\scratch_work\threading_guide_script_cursors.py", line 9, in insert_from_thread
    results_df_dict[thread_name] = duckdb_cursor.execute("""INSERT INTO my_inserts VALUES (?)""", (thread_name,)).df()
RuntimeError: DuckDB objects created in a thread can only be used in that same thread. The object was created in thread id 6957052318446529075 and this is thread id 16193784251867083840
```

2. Use a persistent DuckDB and just pass the path to the thread. Make a connection and cursor from that persistent DB path in each thread.
```python
import duckdb
from threading import Thread, current_thread
import pandas as pd

def insert_from_thread(duckdb_path, results_df_dict):
  # Insert a row with the name of the thread
#   duckdb_cursor = duckdb.connect(duckdb_path).cursor()
  duckdb_cursor = duckdb.connect(duckdb_path, check_same_thread=False).cursor()
  # duckdb_conn = duckdb.connect(duckdb_path, check_same_thread=False)
  thread_name = str(current_thread().name)
  results_df_dict[thread_name] = duckdb_cursor.execute("""INSERT INTO my_inserts VALUES (?)""", (thread_name,)).df()
  # results_df_dict[thread_name] = duckdb_conn.execute("""INSERT INTO my_inserts VALUES (?)""", (thread_name,)).df()

duckdb_path = 'another_test_10.duckdb'
duckdb_con = duckdb.connect(duckdb_path, check_same_thread=False)
duckdb_con.execute("""CREATE OR REPLACE TABLE my_inserts (thread_name varchar)""")


thread_count = 3
threads = []
results_df_dict = {}

# Kick off multiple threads (in the same process) 
# Pass in the same connection as an argument, and an object to store the results
for i in range(thread_count):
    threads.append(Thread(target=insert_from_thread,
                            args=(duckdb_path, results_df_dict,),
                            name='my_thread_'+str(i)))

for i in range(thread_count):
    threads[i].start()

for i in range(thread_count):
    threads[i].join()

print(results_df_dict)
print(duckdb_con.execute("""SELECT * FROM my_inserts""").df())
```
```python
Exception in thread my_thread_2:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\new_duckdb\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\new_duckdb\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Alex\Documents\DuckDB\scratch_work\threading_guide_script_cursors_persistent.py", line 8, in insert_from_thread
    duckdb_cursor = duckdb.connect(duckdb_path, check_same_thread=False).cursor()
RuntimeError: IO Error: Cannot open file "another_test_10.duckdb": The process cannot access the file because it is being used by another process.
```

3. Create the cursor from the same connection in the parent thread and pass the cursor to the child thread:
```python
import duckdb
from threading import Thread, current_thread
import pandas as pd

def insert_from_thread(duckdb_cursor, results_df_dict):
  # Insert a row with the name of the thread
  thread_name = str(current_thread().name)
  results_df_dict[thread_name] = duckdb_cursor.execute("""INSERT INTO my_inserts VALUES (?)""", (thread_name,)).df()

duckdb_con = duckdb.connect(check_same_thread=False) # In Memory DuckDB
duckdb_con.execute("""CREATE OR REPLACE TABLE my_inserts (thread_name varchar)""")

thread_count = 3
threads = []
cursors = []
results_df_dict = {}

# Kick off multiple threads (in the same process) 
# Pass in the same connection as an argument, and an object to store the results
for i in range(thread_count):
    cursors.append(duckdb_con.cursor())
    threads.append(Thread(target=insert_from_thread,
                            args=(cursors[i], results_df_dict,),
                            name='my_thread_'+str(i)))

for i in range(thread_count):
    threads[i].start()

for i in range(thread_count):
    threads[i].join()

print(results_df_dict)
print(duckdb_con.execute("""SELECT * FROM my_inserts""").df())
```
```python
Exception in thread my_thread_2:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\new_duckdb\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\new_duckdb\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Alex\Documents\DuckDB\scratch_work\threading_guide_pre_thread_cursors.py", line 8, in insert_from_thread
    results_df_dict[thread_name] = duckdb_cursor.execute("""INSERT INTO my_inserts VALUES (?)""", (thread_name,)).df()
RuntimeError: DuckDB objects created in a thread can only be used in that same thread. The object was created in thread id 12959597083599519063 and this is thread id 9850670642492014805
```

**Comment by pdet** [comment]
Hey @Alex-Monahan, I'm happy to have a go at this next week! Thanks for the detailed use-cases :-)

**Comment by blackrez** [comment]
Why not use `asyncio` ?

Async is lot easier to use than threads. 

Here the (very) basic sample : 

```
import asyncio
import time

import duckdb
import pandas as pd

from random import randint 


con_duckdb = duckdb.connect()
my_df = pd.DataFrame.from_dict({'a': [42]})
con_duckdb.execute("CREATE TABLE my_table AS SELECT * FROM my_df")
cur_duckdb = con_duckdb.cursor()

async def worker(name, queue):
    while True:
        # Get a "work item" out of the queue.
        num = await queue.get()
        my_df = pd.DataFrame.from_dict({'a': [num]})
        cur_duckdb.execute("INSERT INTO my_table SELECT * FROM my_df")

        # Notify the queue that the "work item" has been processed.
        queue.task_done()

async def main():
    # Create a queue that we will use to store our "workload".
    queue = asyncio.Queue()

    # Generate random timings and put them into the queue.
    total_sleep_time = 0
    for _ in range(20):
        sleep_for = randint(0,10)
        total_sleep_time += sleep_for
        queue.put_nowait(sleep_for)

    # Create three worker tasks to process the queue concurrently.
    tasks = []
    for i in range(3):
        task = asyncio.create_task(worker(f'worker-{i}', queue))
        tasks.append(task)

    # Wait until the queue is fully processed.
    started_at = time.monotonic()
    await queue.join()
    total_slept_for = time.monotonic() - started_at

    # Cancel our worker tasks.
    for task in tasks:
        task.cancel()
    # Wait until all worker tasks are cancelled.
    await asyncio.gather(*tasks, return_exceptions=True)
    r = cur_duckdb.execute("SELECT * FROM my_table")
    print(r.fetchdf())

asyncio.run(main())
```

(Hope it could help)

**Comment by Mause** [comment]
All calls to the duckdb python API are blocking, so you can't really use it efficiently with asyncio without the event loop being blocked (unless of course you call duckdb from threads and do everything else in asyncio)

**Comment by Alex-Monahan** [comment]
Closing thanks to guide in #433 . Feedback is welcome on that guide!
