### ISSUE TITLE
Issue found SQL on Pandas

### ISSUE THREAD

**Issue by antonylebechec** [duckdb/duckdb-web#3726]
Dear duckDB team,

I used to deal with duckdb 1.0.0. With this version, using a dataframe as a table is easy, and within a function. However, using version 1.1.1, it dos not work anymore. Let me explain:
```python

# Construct dataframe
mydf = pd.DataFrame({"a": [1, 2, 3]})

# Query dataframe - OK for both versions 1.0.0 and 1.1.1
duckdb.query("SELECT sum(a) FROM mydf").to_df())

# Query dataframe using a function - OK with 1.0.0 - KO with version 1.1.1 !!!
self.query(query="SELECT sum(a) FROM mydf"))

Traceback (most recent call last):
...
duckdb.duckdb.CatalogException: Catalog Error: Table with name mydf does not exist!
```

Does it mean that a dataframe is not shared with a 'sub-function' anymore?

**Comment by antonylebechec** [comment]
Sorry, that was a poorly made message...

First of all, a python script 'test.py':
```python
import duckdb
import pandas

class test:
    """ """

    def __init__(self):
        """ """

        print(f"duckDB release: {duckdb.__version__}")

    def query(self, query):
        """ """

        return duckdb.query(query)

    def df_query(self):
        """ """

        # Create a Pandas dataframe
        my_df = pandas.DataFrame.from_dict({"a": [42]})

        # query the Pandas DataFrame "my_df"
        print("duckDB query Pandas DataFrame:")
        print(duckdb.sql("SELECT * FROM my_df").df())

        # query the Pandas DataFrame "my_df" through query function
        print("duckDB query Pandas DataFrame through query function:")
        print(self.query(query="SELECT * FROM my_df").df())


# Main
t = test()
t.df_query()

```

Then, command lines:
```bash
pip install duckdb==1.0.0
python test.py
pip install duckdb==1.1.1
python test.py
```

Finally, the result:
```bash
$ pip install duckdb==1.0.0
Collecting duckdb==1.0.0
...
Successfully installed duckdb-1.0.0
$ python test.py
duckDB release: 1.0.0
duckDB query Pandas DataFrame:
    a
0  42
duckDB query Pandas DataFrame through query function:
    a
0  42
$ pip install duckdb==1.1.1
Collecting duckdb==1.1.1
...
Successfully installed duckdb-1.1.1
$ python test.py
duckDB release: 1.1.1
duckDB query Pandas DataFrame:
    a
0  42
duckDB query Pandas DataFrame through query function:
Traceback (most recent call last):
  File "/tools/howard/0.11.0/tmp/test.py", line 35, in <module>
    t.df_query()
  File "/tools/howard/0.11.0/tmp/test.py", line 30, in df_query
    print(self.query(query="SELECT * FROM my_df").df())
  File "/tools/howard/0.11.0/tmp/test.py", line 16, in query
    return duckdb.query(query)
duckdb.duckdb.CatalogException: Catalog Error: Table with name my_df does not exist!
Did you mean "pragma_databa

```
