### ISSUE TITLE
python document is out-of-date

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb-web#572]
https://duckdb.org/docs/api/python/overview
says
```
import duckdb
r1 = duckdb.sql('SELECT 42 AS i')
duckdb.sql('SELECT i * 2 AS k FROM r1').show()
```
in my python duckdb 
```
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:34:34) [MSC v.1928 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import duckdb
>>> r1 = duckdb.sql('SELECT 42 AS i')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'duckdb' has no attribute 'sql'
>>> duckdb.sql('SELECT i * 2 AS k FROM r1').show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'duckdb' has no attribute 'sql'
>>> dir(duckdb)
['BinderException', 'CastException', 'CatalogException', 'ConnectionException', 'ConstraintException', 'ConversionException', 'DataError', 'DuckDBPyConnection', 'DuckDBPyRelation', 'Error',
'FatalException', 'IOException', 'IntegrityError', 'InternalError', 'InternalException', 'InterruptException', 'InvalidInputException', 'InvalidTypeException', 'NotImplementedException', 'No
tSupportedError', 'OperationalError', 'OutOfMemoryException', 'OutOfRangeException', 'ParserException', 'PermissionException', 'ProgrammingError', 'SequenceException', 'SerializationExceptio
n', 'StandardException', 'SyntaxException', 'TransactionException', 'TypeMismatchException', 'ValueOutOfRangeException', 'Warning', '__doc__', '__file__', '__git_revision__', '__interactive_
_', '__jupyter__', '__loader__', '__name__', '__package__', '__spec__', '__standard_vector_size__', '__version__', '_clean_default_connection', 'aggregate', 'alias', 'apilevel', 'append', 'a
rrow', 'begin', 'close', 'comment', 'commit', 'connect', 'cursor', 'default_connection', 'description', 'df', 'distinct', 'duplicate', 'execute', 'executemany', 'fetch_arrow_table', 'fetch_d
f', 'fetch_df_chunk', 'fetch_record_batch', 'fetchall', 'fetchdf', 'fetchmany', 'fetchnumpy', 'fetchone', 'filter', 'from_arrow', 'from_csv_auto', 'from_df', 'from_parquet', 'from_query', 'f
rom_substrait', 'from_substrait_json', 'get_substrait', 'get_substrait_json', 'get_table_names', 'identifier', 'install_extension', 'keyword', 'limit', 'load_extension', 'numeric_const', 'op
erator', 'order', 'paramstyle', 'project', 'query', 'query_df', 'register', 'rollback', 'string_const', 'table', 'table_function', 'threadsafety', 'token_type', 'tokenize', 'unregister', 'va
lues', 'view', 'write_csv']
>>> duckdb.__version__
'0.6.2-dev710'
```

**Comment by l1t1** [comment]
my mistake
duckdb 0.70 works
```
C:\Users\Administrator>pip install duckdb -U
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: duckdb in d:\python\lib\site-packages (0.6.2.dev710)
Collecting duckdb
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/45/b5/fe3f0d5163a121f2968aa847acbe5dc11ae9a2b89b3849c2999549c929cd/duckdb-0.7.0-cp38-cp38-win32.whl (8.4 MB)
     |████████████████████████████████| 8.4 MB 159 kB/s
Installing collected packages: duckdb
  Attempting uninstall: duckdb
    Found existing installation: duckdb 0.6.2.dev710
    Uninstalling duckdb-0.6.2.dev710:
      Successfully uninstalled duckdb-0.6.2.dev710
Successfully installed duckdb-0.7.0

C:\Users\Administrator>python
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:34:34) [MSC v.1928 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import duckdb
>>> r1 = duckdb.sql('SELECT 42 AS i')
>>> duckdb.sql('SELECT i * 2 AS k FROM r1').show()
┌───────┐
│   k   │
│ int32 │
├───────┤
│    84 │
└───────┘

```
